#ifndef CAMYUPROPERTYEDIT_GLOBAL_H
#define CAMYUPROPERTYEDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CAMYUPROPERTYEDIT_LIB
# define CAMYUPROPERTYEDIT_EXPORT Q_DECL_EXPORT
#else
# define CAMYUPROPERTYEDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMYUPROPERTYEDIT_GLOBAL_H
